export const  photos =
{ avatar_1 : require("../assets/images/avatar-1.jpg"),
 avatar_2 : require("../assets/images/avatar-2.jpg"),
 avatar_3 : require("../assets/images/avatar-3.jpg"),
 avatar_4 : require("../assets/images/avatar-4.jpg"),
 avatar_5 : require("../assets/images/avatar-5.jpg"),
 baked_fries : require("../assets/images/baked-fries.jpg"),
 burger_restaurant_1 : require("../assets/images/burger-restaurant.jpg"),
 burger_restaurant_2 : require("../assets/images/burger-restaurant-2.jpg"),
 chicago_hot_dog : require("../assets/images/chicago-hot-dog.jpg"),
 crispy_chicken_burger : require("../assets/images/crispy-chicken-burger.jpg"),
 fries_restaurant : require("../assets/images/fries-restaurant.jpg"),
 hawaiian_pizza : require("../assets/images/hawaiian-pizza.jpg"),
 honey_mustard_chicken_burger : require("../assets/images/honey-mustard-chicken-burger.jpg"),
 hot_dog_restaurant : require("../assets/images/hot-dog-restaurant.jpg"),
 ice_kacang : require("../assets/images/ice-kacang.jpg"),
 japanese_restaurant : require("../assets/images/japanese-restaurant.jpg"),
 kek_lapis_shop : require("../assets/images/kek-lapis-shop.jpg"),
 kek_lapis : require("../assets/images/kek-lapis.jpg"),
 kolo_mee : require("../assets/images/kolo-mee.jpg"),
 nasi_briyani_mutton : require("../assets/images/nasi-briyani-mutton.jpg"),
 nasi_lemak : require("../assets/images/nasi-lemak.jpg"),
 noodle_shop : require("../assets/images/noodle-shop.jpg"),
 pizza_restaurant : require("../assets/images/pizza-restaurant.jpg"),
 pizza : require("../assets/images/pizza.jpg"),
 salad : require("../assets/images/salad.jpg"),
 sarawak_laksa : require("../assets/images/sarawak-laksa.jpg"),
 sushi : require("../assets/images/sushi.jpg"),
 teh_c_peng : require("../assets/images/teh-c-peng.jpg"),
 tomato_pasta : require("../assets/images/tomato-pasta.jpg"),}

 export default photos;
// export default {
//     avatar_1,
//     avatar_2,
//     avatar_3,
//     avatar_4,
//     avatar_5,
//     baked_fries,
//     burger_restaurant_1,
//     burger_restaurant_2,
//     chicago_hot_dog,
//     crispy_chicken_burger,

//     fries_restaurant,
//     hawaiian_pizza,
//     honey_mustard_chicken_burger,
//     hot_dog_restaurant,
//     ice_kacang,

//     japanese_restaurant,
//     kek_lapis_shop,
//     kek_lapis,
//     kolo_mee,
//     nasi_briyani_mutton,
//     nasi_lemak,
//     noodle_shop,
//     pizza_restaurant,
//     pizza,
//     sarawak_laksa,
//     sushi,
//     teh_c_peng,
//     tomato_pasta,
// }